name: sky_map
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  location: ^7.0.0
  geolocator: ^12.0.0
  vector_math: ^2.1.4
  tilt: ^0.0.2
  flutter_compass: ^0.8.0
  permission_handler: ^11.3.1
  sensors_plus: ^1.4.1
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  touchable: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
